let bookTitle: string ="TypeScript Basics"
let libraryName: string="My Library"
let numberOfBooks: number= 8
let isLibraryOpen: boolean=true

let titulo:string= "Veronika decide morir"
let autor:string= "Paulo Coelho"
let genero:string= "Superación personal"
let idioma:string= "Español"
let precio:number= 35000
let formato:string= "Tapa blanda"
let isbn:string= "978-0061124266"
let descripcion:string= "Una joven decide quitarse la vida, pero termina internada en un hospital psiquiátrico donde descubre un nuevo sentido para su existencia."
let estado:string= "Nuevo"
let ubicacion:string= "Sección de Desarrollo Personal"
let fecha_publicacion:string= "1998"
let editorial:string= "Debolsillo"
let paginas:number= 240
let dimensiones:string= "13.5 x 20.5 cm"
let peso:string= "250 g"
let disponible:boolean=true